ALTER TABLE campaign_metrics
  ADD COLUMN IF NOT EXISTS conversations  INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS profile_visits INTEGER DEFAULT 0;

ALTER TABLE ad_metrics
  ADD COLUMN IF NOT EXISTS conversations  INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS profile_visits INTEGER DEFAULT 0;
